# Assignment

1. Create an array of shape (10, 10) with uint8 random values.
2. print the shape, size and dimension, 
3. Compute the sum of the third row to the last.
4. Compute the average of the columns

In [1]:
# 1. Create an array of shape (10,10) with uint8 random values


In [3]:
import numpy as np
ar10x10 = np.random.randint(0, 255, (10, 10), dtype='uint8')
ar10x10


array([[141, 136, 184,  22, 217, 170,  95, 132, 122, 142],
       [127, 177,  40,   6, 128, 245, 192,  69, 244, 152],
       [105, 118, 139, 134, 118, 197, 170, 140, 194, 245],
       [248,  21, 178, 164, 234,  26, 101,  95,  26,  99],
       [238,  53, 153,  20, 103, 175, 208,  76, 204,  22],
       [ 90, 193, 130,  88, 202,  84, 127, 189, 123, 217],
       [113,  60, 117,  30, 244, 109, 226, 142,  70, 156],
       [  3, 156,  53, 109,  87, 190,  83,  10, 213, 143],
       [ 78, 133, 134, 104,  53, 104, 126, 166, 138, 131],
       [207, 131, 158, 222, 247, 167, 239, 213, 192, 198]], dtype=uint8)

In [8]:
# 2. print the shape, size and dimension
shape = ar10x10.shape
shape


(10, 10)

In [9]:
size = ar10x10.size
size


100

In [10]:
ndim = ar10x10.ndim
ndim


2

In [14]:
print("Shape is {0}\nSize is {1}\nDimension is {2}".format(
    shape, size, ndim))


Shape is (10, 10)
Size is 100
Dimension is 2


In [15]:
print(f"Shape is {shape}\nSize is {size}\nDimension is {ndim}")

Shape is (10, 10)
Size is 100
Dimension is 2


In [16]:
#3. compute the sum of third row to last

In [17]:
row3fromlast = ar10x10[-3]
row3fromlast

array([  3, 156,  53, 109,  87, 190,  83,  10, 213, 143], dtype=uint8)

In [18]:
row3tolast = ar10x10[3:]
row3tolast

array([[248,  21, 178, 164, 234,  26, 101,  95,  26,  99],
       [238,  53, 153,  20, 103, 175, 208,  76, 204,  22],
       [ 90, 193, 130,  88, 202,  84, 127, 189, 123, 217],
       [113,  60, 117,  30, 244, 109, 226, 142,  70, 156],
       [  3, 156,  53, 109,  87, 190,  83,  10, 213, 143],
       [ 78, 133, 134, 104,  53, 104, 126, 166, 138, 131],
       [207, 131, 158, 222, 247, 167, 239, 213, 192, 198]], dtype=uint8)