# Assignment - Index splitting (take home)

1. Create an array of shape (100,100,3) of unsigned integer 8 bits filled with random values between 0 to 256.
2. Find the values that are less than 30, 50, 100, 250.
3. Split the array into 4 parts vertically and horizontally
4. Copy array from Question 1 and change the values that are les than 110 to 0 and others to 255
5. Hint: Use random seed of 12345

In [2]:
import numpy as np

In [3]:
np.random.seed(12345)
ar100x100x3 = np.random.randint(0,255,(100,100,3),dtype=np.uint8)

In [4]:
a30 = ar100x100x3<30
ar100x100x3[a30]
# print(a30)

array([29,  8, 21, ..., 17, 26,  7], dtype=uint8)

In [5]:
a50 = ar100x100x3 < 50
print(ar100x100x3[a30])
# print(a30)


[29  8 21 ... 17 26  7]


In [6]:
a100 = ar100x100x3 < 100
print(ar100x100x3[a100])

[81 45 29 ... 75 54 64]


In [7]:
a250 = ar100x100x3 < 250
print(ar100x100x3[a250])
#print(a50)

[226  81 237 ...  54  64 120]


In [8]:
a_4h = np.hsplit(ar100x100x3,4)
print(len(a_4h))

4


In [9]:
a_4v = np.vsplit(ar100x100x3,4)
print(len(a_4v))

4


In [10]:
a_5h = np.hsplit(ar100x100x3,4)
print(len(a_4h))

4


In [11]:
aryNew = ar100x100x3.copy()
aryNew = np.where(aryNew<110,0,255)
print(aryNew)

[[[255   0 255]
  [255 255   0]
  [255 255   0]
  ...
  [255 255 255]
  [255 255 255]
  [  0   0   0]]

 [[  0 255 255]
  [255   0 255]
  [  0 255   0]
  ...
  [  0 255 255]
  [  0 255 255]
  [255   0   0]]

 [[255   0 255]
  [  0   0 255]
  [  0 255   0]
  ...
  [  0 255 255]
  [255   0   0]
  [255 255 255]]

 ...

 [[255 255 255]
  [  0   0 255]
  [255 255 255]
  ...
  [  0   0   0]
  [255   0 255]
  [255 255 255]]

 [[255 255 255]
  [255 255   0]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [  0   0   0]]

 [[  0   0   0]
  [255 255   0]
  [  0 255 255]
  ...
  [  0   0 255]
  [  0   0   0]
  [  0   0 255]]]
