# Assignment

1. Create a random array A, using randint seed 2 of shape (6x6).
2. Convert the array A, to  an identity matrix $I$.

$$
I = 
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}
$$

$$
A.A^{-1} = A^{-1}.A = I
$$

In [3]:
import numpy as np

I = np.eye(6)

np.random.seed = 2
A = np.random.randint(1,10,(6,6),dtype='uint8')

In [5]:
I

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [4]:
A

array([[7, 4, 3, 5, 6, 1],
       [1, 5, 8, 9, 1, 7],
       [8, 7, 4, 7, 8, 5],
       [9, 4, 1, 9, 1, 3],
       [5, 1, 1, 4, 2, 3],
       [8, 9, 2, 3, 4, 7]], dtype=uint8)

In [6]:
invA = np.linalg.inv(A)
invA

array([[ 0.28378618,  0.00284141, -0.31495294, -0.0426212 ,  0.20049725,
         0.11392293],
       [-0.04857041, -0.00736992,  0.08253419,  0.11054875, -0.36378974,
         0.06388741],
       [ 0.4557805 ,  0.14411295, -0.42714438, -0.16169419,  0.13771977,
         0.10615344],
       [-0.22509323, -0.01038892,  0.26092168,  0.15583378, -0.13931806,
        -0.1509057 ],
       [-0.13603268, -0.06268869,  0.29239922, -0.05966969,  0.01402948,
        -0.10717457],
       [-0.21790091,  0.00532765,  0.09696324, -0.07991476,  0.25093234,
         0.02610549]])

In [13]:
C = A @ invA
C = np.round(C).astype(int)
C

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [15]:
C2 = invA @ A
C2 = np.round(C2).astype(int)
C2

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [16]:
C==I

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])